=== 502502502/Community/src/main/resources/templates/XMLwork/personList.dtd
<!--      人员列表,包含若干人-->
        <!ELEMENT persons (person)*>
<!--      人元素,包含姓名,编号,性别,地址和若干电话-->
        <!ELEMENT person (name,no,sex,address,phone*)>
<!--      电话号码的数量,用于设置跨行数-->
        <!ATTLIST person phoneCount CDATA  "1">
<!--      电话,包含号码和类型-->
        <!ELEMENT phone (phonenumber,phonetype)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT no (#PCDATA)>
        <!ELEMENT sex (#PCDATA)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT phonenumber (#PCDATA)>
        <!ELEMENT phonetype (#PCDATA)>

=== 502502502/Community/src/main/resources/templates/XMLwork/personList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 外部引入DTD -->
<!DOCTYPE persons SYSTEM "personList.dtd">
<!--引用XSL显示数据-->
<?xml-stylesheet type="text/xsl" href="personList.xsl"?>


<!--XML描述-->
<persons>
    <person phoneCount="2">
        <name>李倩倩</name>
        <no>10191101</no>
        <sex>女</sex>
        <address>前卫胡同 126 号</address>
        <phone>
            <phonenumber>88662255</phonenumber>
            <phonetype>住宅</phonetype>
        </phone>
        <phone>
            <phonenumber>13012345678</phonenumber>
            <phonetype>移动电话</phonetype>
        </phone>
    </person>
    <person phoneCount="1">
        <name>王晓明</name>
        <no>10191203</no>
        <sex>男</sex>
        <address>北京大街 103 号</address>
        <phone>
            <phonenumber>85943212</phonenumber>
            <phonetype>办公</phonetype>
        </phone>
    </person>
</persons>
