=== 502502502/Community/src/main/resources/templates/XMLwork/score.dtd
<!--DTD定义-->

<!--        根元素，包含若干学生-->
        <!ELEMENT students (student)*>
<!--        学生元素，包含姓名，平均成绩和课程成绩-->
        <!ELEMENT student (name,avgscore,course*)>
<!--        课程成绩包含课程名称，课程成绩，录入时间-->
        <!ELEMENT course (title,score,date)>

        <!ELEMENT name (#PCDATA)>
        <!ATTLIST name rowspan CDATA  "1">
        <!ELEMENT avgscore (#PCDATA)>
        <!ATTLIST avgscore rowspan CDATA  "1">
        <!ELEMENT title (#PCDATA)>
        <!ATTLIST title rowspan CDATA  "1">
        <!ELEMENT score (#PCDATA)>
        <!ATTLIST score rowspan CDATA  "1">
        <!ELEMENT date (#PCDATA)>
        <!ATTLIST date rowspan CDATA  "1">

=== 502502502/Community/src/main/resources/templates/XMLwork/score.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 外部引入DTD -->
<!DOCTYPE students SYSTEM "score.dtd">
<!--引用XSL显示数据-->
<?xml-stylesheet type="text/xsl" href="score.xsl"?>

<!--XML描述-->
<students>
    <student>
        <name rowspan="3">张三</name>
        <avgscore rowspan="3"></avgscore>
        <course>
            <title>编译方法</title>
            <score>79</score>
            <date>2022/11/19</date>
        </course>
        <course>
            <title>C程序设计</title>
            <score>85</score>
            <date>2022/11/19</date>
        </course>
        <course>
            <title>数据结构</title>
            <score>93</score>
            <date>2022/11/19</date>
        </course>
    </student>
    <student>
        <name rowspan="3">李四</name>
        <avgscore rowspan="3"></avgscore>
        <course>
            <title>计算复杂性</title>
            <score>72</score>
            <date>2022/11/19</date>
        </course>
        <course>
            <title>偏微分方程</title>
            <score>86</score>
            <date>2022/11/19</date>
        </course>
        <course>
            <title>计算方法</title>
            <score>95</score>
            <date>2022/11/19</date>
        </course>
    </student>
    <student>
        <name rowspan="4">王五</name>
        <avgscore rowspan="4"></avgscore>
        <course>
            <title>分子轨道理论</title>
            <score>79</score>
            <date>2022/11/19</date>
        </course>
        <course>
            <title>有机化学</title>
            <score>80</score>
            <date>2022/11/19</date>
        </course>
        <course>
            <title>分子生物学</title>
            <score>88</score>
            <date>2022/11/19</date>
        </course>
        <course>
            <title>无机化学</title>
            <score>98</score>
            <date>2022/11/19</date>
        </course>
    </student>
</students>
